// <auto-generated />
namespace PlaySchool.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FirstAndLastName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FirstAndLastName));
        
        string IMigrationMetadata.Id
        {
            get { return "201705030236409_FirstAndLastName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
